version: "3"

services:
  hello:
    build: ./src/hello
    image: hello:latest
    container_name: hello
    hostname: hello
    networks:
     - hello-world-net
    # volumes:
    #  - "./src/hello/main.py:/app/main.py"
    working_dir: /app
    ports:
     - "80:80"
    environment:
     - WORLD_ADDR=world
     - WORLD_PORT=8081
    # command: python main.py

  world:
    build: ./src/world
    image: world:latest
    container_name: world
    hostname: world
    networks:
     - hello-world-net
    environment:
     - WORLD_PORT=8081
    # volumes:
    #  - "./src/world/main.go:/app/main.go"
    working_dir: /app
    # command: go run main.go

networks:
  hello-world-net: