version: "3"

services:
  hello:
    image: kjanshair/hello:latest
    container_name: hello
    hostname: hello
    networks:
     - hello-world-net
    ports:
     - "80:80"
    environment:
     - WORLD_ADDR=world
     - WORLD_PORT=8081

  world:
    image: kjanshair/world:latest
    container_name: world
    hostname: world
    networks:
     - hello-world-net
    environment:
     - WORLD_PORT=8081

networks:
  hello-world-net:
