apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: world-deployment
spec:
  selector:
    matchLabels:
      app: world
  replicas: 1
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - name: world
        image: kjanshair/world:latest
        env:
          - name: WORLD_PORT
            value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: world-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: world
