# Default values for ping.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hello:
  deployment:
    name: hello
    image:
      repository: kjanshair/hello
      tag: latest
      pullPolicy: IfNotPresent
    replicaCount: 1
  service:
    type: LoadBalancer
    port: 80

world:
  deployment:
    name: world
    image:
      repository: kjanshair/world
      tag: latest
      pullPolicy: IfNotPresent
    replicaCount: 1
  service:
    type: ClusterIP
    port: 80


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
