apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hello.service.name }}
  labels:
    app: {{ template "hello.name" . }}
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.hello.service.type }}
  ports:
    - port: {{ .Values.hello.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "hello.name" . }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.world.service.name }}
  labels:
    app: {{ template "world.name" . }}
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.world.service.type }}
  ports:
    - port: {{ .Values.world.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "world.name" . }}